[package]
name = "jiggler"
version = "1.0.2"
edition = "2024"

[dependencies]
enigo = "0.6.1"
eframe = "0.33.3"
egui = "0.33.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true